---

- name: Manage SSH keys for monitoring and site synchronization
  include: ssh_keys.yml
  with_items: '{{ checkmk_server__sites }}'
  loop_control:
    loop_var: site_item

- name: Re-read local facts
  action: setup

- name: Setup SSH public key login on slave sites
  include: ssh_login.yml
  with_items: '{{ checkmk_server__sites }}'
  loop_control:
    loop_var: site_item
