---
# IMPORTANT:
# These tasks are run for each Check_MK site defined
# in `checkmk_server__sites`. This means they can run multiple
# times per server. If the monitoring site is a remote slave,
# they might even run on a different server. The site configuration
# is available through `site_item`.

- block:

  - name: Allow SSH login from master site
    authorized_key:
      user: '{{ site_item.user }}'
      key: '{{ item.ssh_public_key }}'
    when: item.name == site_item.master_site
    with_items: '{{ hostvars[site_item.master_delegate_to].ansible_local.checkmk_server
                    if ("master_delegate_to" in site_item.keys()) else [] }}'

  # delegate block
  delegate_to: '{{ site_item.delegate_to
                   if (not site_item.delegate_to == inventory_hostname) else omit }}'
