---
#
# Check_MK multisite/WATO configuration
#

- name: Query installed Check_MK packages
  command: mkp list
  become_user: '{{ checkmk_server__user }}'
  become_flags: '-i'
  changed_when: False
  always_run: True
  register: checkmk_server__register_mkp
  tags:
    - 'role::checkmk_server:mkp'

- name: Download Check_MK packages
  get_url:
    url: '{{ item.url }}'
    dest: '{{ checkmk_server__site_home }}/tmp'
    checksum: '{{ item.checksum|d(omit) }}'
  when: ('url' in item) and
        (item.name not in checkmk_server__register_mkp.stdout_lines)
  register: checkmk_server__register_mkp_download
  with_items: '{{ checkmk_server__site_packages }}'
  tags:
    - 'role::checkmk_server:mkp'

- name: Upload Check_MK packages
  copy:
    src: '{{ item.path }}'
    dest: '{{ checkmk_server__site_home }}/tmp'
  when: ('path' in item) and
        (item.name not in checkmk_server__register_mkp.stdout_lines)
  register: checkmk_server__register_mkp_upload
  with_items: '{{ checkmk_server__site_packages }}'
  tags:
    - 'role::checkmk_server:mkp'

- name: Install Check_MK packages
  command: mkp install '{{ item.dest|d() }}'
  become_user: '{{ checkmk_server__user }}'
  become_flags: '-i'
  when: not (item | skipped)
  with_flattened:
    - '{{ checkmk_server__register_mkp_download.results }}'
    - '{{ checkmk_server__register_mkp_upload.results }}'
  tags:
    - 'role::checkmk_server:mkp'

- name: Generate Check_MK WATO multisite definitions
  template:
    src: '{{ lookup("template_src", "etc/check_mk/multisite.d/wato/" + item | basename) }}'
    dest: '{{ checkmk_server__site_home }}/{{ checkmk_server__multisite_config_path }}/wato/{{ item | basename | replace(".j2", "") }}'
    owner: '{{ checkmk_server__user }}'
    group: '{{ checkmk_server__group }}'
    mode: '{{ "0660"
              if item | basename | replace(".j2", "") in [ "hosttags.mk", "users.mk", "user_connections.mk" ]
              else "0644" }}'
  with_fileglob: [ '../templates/etc/check_mk/multisite.d/wato/*.mk.j2' ]
  notify: [ 'Reload Check_MK configuration' ]
  tags: [ 'role::checkmk_server:rules', 'role::checkmk_server:multisite' ]

- name: Generate Check_MK custom multisite definitions
  template:
    src: 'etc/check_mk/multisite.d/custom.mk.j2'
    dest: '{{ checkmk_server__site_home }}/{{ checkmk_server__multisite_config_path }}/{{ item["filename"] }}'
    owner: '{{ checkmk_server__user }}'
    group: '{{ checkmk_server__group }}'
    mode: '0644'
  with_items: '{{ checkmk_server__multisite_config_map }}'
  when: not item['wato']|d(True)
  notify: [ 'Reload Check_MK configuration' ]
  tags: [ 'role::checkmk_server:rules', 'role::checkmk_server:multisite' ]

- name: Generate Check_MK WATO monitoring definitions
  template:
    src: '{{ lookup("template_src", "etc/check_mk/conf.d/wato/" + item | basename) }}'
    dest: '{{ checkmk_server__site_home }}/{{ checkmk_server__site_config_path }}/wato/{{ item | basename | replace(".j2", "") }}'
    owner: '{{ checkmk_server__user }}'
    group: '{{ checkmk_server__group }}'
    mode: '{{ "0660"
              if item | basename | replace(".j2", "") in [ "contacts.mk" ]
              else "0644" }}'
  with_fileglob: [ '../templates/etc/check_mk/conf.d/wato/*.mk.j2' ]
  notify: [ 'Reload Check_MK configuration' ]
  tags: [ 'role::checkmk_server:rules' ]

- name: Generate Check_MK custom monitoring definitions
  template:
    src: 'etc/check_mk/conf.d/custom.mk.j2'
    dest: '{{ checkmk_server__site_home }}/{{ checkmk_server__site_config_path }}/{{ item["filename"] }}'
    owner: '{{ checkmk_server__user }}'
    group: '{{ checkmk_server__group }}'
    mode: '0644'
  with_items: '{{ checkmk_server__site_config_map }}'
  when: not item['wato']|d(True)
  notify: [ 'Reload Check_MK configuration' ]
  tags: [ 'role::checkmk_server:rules' ]
