---

- name: Create Check_MK site
  command: omd create '{{ site_item.name }}'
  args:
    creates: '{{ site_item.home }}/etc/omd/site.conf'
  delegate_to: '{{ site_item.delegate_to
                   if (not site_item.delegate_to == inventory_hostname) else omit }}'
